CREATE TABLE USERS (
    USER_ID VARCHAR2(50) PRIMARY KEY,
    USERNAME VARCHAR2(100),
    DOB DATE,
    PASSWORD VARCHAR2(50),
    QUESTION1 VARCHAR2(200),
    ANSWER1 VARCHAR2(200),
    QUESTION2 VARCHAR2(200),
    ANSWER2 VARCHAR2(200),
    PASSWORD_CHANGE_DATE DATE
);
Desc USERS;
SELECT * FROM USERS;
